AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/**/*'
    - 'db/**/*.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'log/**/*'

Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 15
Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
  - 'test/**/*.rb'
Layout/LineLength:
  Exclude:
  - 'test/**/*.rb'
